### ISSUE TITLE
Plan for v1.1

### ISSUE THREAD

**Issue by timqian** [timqian/chart.xkcd#6]
## Features

- [x] install via npm **(PR #7)**
- [x] smaller bundle size **(PR #7 468KB => 68KB)**
- [x] options tick numbers etcs #5 #11 **(PR #12)**
  for line chart & bar chart, it is not possible to specify tick numbers in the current implementation as I am using scalePoint method of D3([ref](https://observablehq.com/@d3/d3-scalepoint)), But it is possible for XY chart.
  update: we can not specify tick number, but can rotate the tick text when there are too many ticks ([ref](https://www.d3-graph-gallery.com/graph/custom_axis.html#axislabels))
- [x] label spacing depend on label size instead of hard coded numbers
- [ ] ~API to update chart~
To update the chart, redrawing it seem enough for now
- [x] Documentation of APIs
- [ ] ~UI to export svg~
Not part of chart.xkcd

### New charts

- [x] XY chart scatter or line **(PR #12)**
- [ ] Radar  #2
- [x] ~Seprate Pie&Doughnut chart ?~ https://timqian.com/chart.xkcd/#pie_doughnut_chart.customize_chart_by_defining_options

## Bugs Fix

- [x] display issue on Safari #3

**Comment by ianbruton** [comment]
Hi! Great project! 

My only suggestion at the moment would be to see if you can apply any antialiasing to the resulting chart, it will make the chart much more visually similar to xkcds sryle.

Keep up the great work

**Comment by ChildishGiant** [comment]
Would the API to update chart allow for the chart to be resized or do you mean update the data in the chart?

**Comment by timqian** [comment]
@ianbruton Thanks, I use SVG filter for now, which add the effect based on pixels. I will try to find ways to improve the effect in v1.2

@ChildishGiant The API to update the chart means updating the data. 

By resizing, do you mean resizing the chart when window size changes? This sort of resizing should be automatically done, I might add it in v1.2

**Comment by ChildishGiant** [comment]
Yea I that's what I mean. Other chart libs need updating manually when scaling, glad to see this is planned
